@startuml


title Create Review
actor Customer as c
participant Dashboard as dsb
participant CreateReviewActivity as cra
database Reviews as rdb

c -> dsb : submit review form
dsb -> cra : create review request

alt if review feedback contains invalid characters
   cra --> dsb : throw InvalidAttributeValueException
   dsb --> c : Review feedback must not contain invalid characters!
end

cra -> rdb : createReviewRequest(Service)
rdb --> cra : review = createReviewRequest(Service)
cra --> dsb : createReviewResult(review)
dsb --> c : Review Successfully Created!


@enduml