package main.java.org.service.message.dynamodb.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "messages")
public class UserMessage {
    private String messageId;
    private String inboxId;
    private String messageBody;
    private String dateTime;
    private String senderUaid;
    private String receiverUaid;
    @DynamoDBRangeKey(attributeName = "inbox_id")
    public String getInboxId() {
        return inboxId;
    }

    public void setInboxId(String inboxId) {
        this.inboxId = inboxId;
    }
    @DynamoDBHashKey(attributeName = "message_id")
    @DynamoDBAutoGeneratedKey
    public String getMessageId() {
        return messageId;
    }

    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    @DynamoDBAttribute(attributeName = "message_body")
    public String getMessageBody() {
        return messageBody;
    }

    public void setMessageBody(String messageBody) {
        this.messageBody = messageBody;
    }
    @DynamoDBAttribute(attributeName = "date_time")
    @DynamoDBAutoGeneratedTimestamp
    public String getDateTime() {
        return dateTime;
    }

    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }
    @DynamoDBAttribute(attributeName = "sender_uaid")
    public String getSenderUaid() {
        return senderUaid;
    }

    public void setSenderUaid(String senderUaid) {
        this.senderUaid = senderUaid;
    }
    @DynamoDBAttribute(attributeName = "receiver_uaid")
    public String getReceiverUaid() {
        return receiverUaid;
    }

    public void setReceiverUaid(String receiverUaid) {
        this.receiverUaid = receiverUaid;
    }
}
